### ISSUE TITLE
Can't Play RTSP With Basic Authentication.

### ISSUE THREAD

**Issue by fikriefs** [pengyanb/com.pengyanb.vlcstreamplayer#1]
com.pengyanb.vlcstreamplayer version 1.0.1
cordova version 6.1.0

I can play video from public RTSP url. BUT when I try to play RTSP url with basic authentication ( ex:  rtsp://user:pass@url ), the player show popup error "Can't play this video". But not triggering the failed callback

`
var videoUrl = "rtsp://user:pass@xx.xx.xx.xx/profile2/media.smp";
window.PYB.vlcStreamPlayer.openPlayerForStreamURL(
function() {
console.log("success");
}, 
function() {
console.log("failed");
}, 
videoUrl);`

**Comment by pengyanb** [comment]
@fikriefs Can you double check if the stream you are trying to play is on port 80? 

The default port for RTSP is 554. Does "rtsp://user:pass@xx.xx.xx.xx:554/profile2/media.smp" solve the issue? 

Also, for a quick test, you can download a VLC Player from App Store to test if that URL is working.

**Comment by fikriefs** [comment]
@pengyanb Thank you for replying my question. I have tried both use port 554 or not (because the default port for RTSP is 554).

It is playing normally in vlc player. But still get error when applying in the plugin. Is there any setting that I miss?

**Comment by pengyanb** [comment]
@fikriefs What was the error message you were getting? Did it say "**Your input can't be opened** VLC is unable to open the MRL ....." or something else. 
As far as I know, the basic authentication shouldn't be the problem. I used this plugin for one of my own project which stream from an IP camera with basic authentication. Could it be the Codec issue?

**Comment by fikriefs** [comment]
@pengyanb The error message is "Can't play this video", bellow is the screenshot 

![screenshot_2016-09-27-11-07-23-455_com sagadio wika](https://cloud.githubusercontent.com/assets/21121925/18900584/ffa51336-856c-11e6-9554-80e92021e97d.png)

Additional info about the rtsp output:
Codec: H.264
Resolution: 800x600
Framerate: 25fps
Maximum bitrate: 2560Kbps, VBR

**Comment by pengyanb** [comment]
@fikriefs I see you are running this plugin on an android device. 
The android part of this plugin is using the native VideoView component, as the RTSP protocol is supported natively by android. However, it depends on a particular build of android system, I noticed there are android systems are built without the necessary codec for decoding some video format.  Check out this link: [http://stackoverflow.com/questions/9870409/cant-play-video-through-rtsp](http://stackoverflow.com/questions/9870409/cant-play-video-through-rtsp)
